name: PRs to master
on: 
  pull_request:
    types: [opened]
    labels:
      required_for_merge:
        # PR is blocked until it has all of these labels
        - ready_to_merge
      block_merge:
        # PR is blocked as long as it has at least one of these labels
        - WIP
        - in_review 
        - to_be_discussed