name: PRs to master
on: 
  pull_request:
    branches: [master]
    types: [closed]
    labels:
      required_for_merge:
        # PR is blocked until it has all of these labels
        - ready_to_merge
      block_merge:
        # PR is blocked as long as it has at least one of these labels
        - WIP
        - in_review 
        - to_be_discussed
jobs:
  merge-master-into-test:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge master back to test
      run: |
          git fetch --unshallow
          git checkout test
          git pull
          git merge --no-ff master -m "Auto-merge master back to test"
          git push
