name: PRs to master
on: 
  pull_request:
    branches: [master]
    types: [closed]
jobs:
  merge-master-into-test:
    if: github.event.pull_request.merged == true
    timeout-minutes: 2
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Merge master back to test
      run: |
          git fetch --unshallow
          git checkout test
          git pull
          git merge --no-ff master -m "Auto-merge master back to test"
          git push
